spring:
  application:
    name: api
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace